export const types = {
    MAIN_TITLE: 'MAIN_TITLE',
    WITH_PARAMS: 'WITH_PARAMS',
    INPUT_VALUE: 'INPUT_VALUE',
    ADD_USERS: 'ADD_USERS',
    DELETE_ALL: 'DELETE_ALL',
    CLEAR_INPUT: 'CLEAR_INPUT'
}